server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: SoftConEx
  datasource:
    url: jdbc:mysql://localhost:3306/softcon_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.softcon.entity
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '接口文档'
      display-name: '接口文档'
      paths-to-match: '/**'
      packages-to-scan: com.softcon.controller
  default-flat-param-object: true
knife4j:
  enable: false
  basic:
    enable: false
    username: user
    password: 123456

